---
- name: Ensure Redis Server working directory exists
  file: path={{ redis_dir }}
        state=directory
        owner=redis
        group=redis
        mode=0750

- name: Configure Redis Server to start at boot
  service: name=redis
           enabled=yes

- name: Check if log file exists
  stat: path={{ redis_logfile }}
  register: redis_logfile_stat

- name: Ensure log file directory exists and has correct owner
  file: path={{ redis_logfile|dirname }}
        state=directory
        owner=redis
        group=redis
        mode=0750
  when: redis_logfile != '""'

- name: Ensure log file exists and is writable by Redis Server
  file: path={{ redis_logfile }}
        state=touch
        owner=redis
        group=redis
        mode=0640
  when: redis_logfile_stat.stat.exists == False and redis_logfile != '""'

- name: Ensure pidfile directory exists and has correct owner
  file: path={{ redis_pidfile|dirname }}
        state=directory
        owner=redis
        group=redis
        mode=0755

# - name: Add Redis Server init config file
#   template: dest=/etc/default/redis-server
#             src=etc/default/redis-server.j2
#             owner=redis
#             group=redis
#             mode=0644
#   notify: restart redis

- name: Ensure config directory exists and has correct owner
  file: path=/etc/redis
        state=directory
        owner=redis
        group=redis
        mode=0750

- name: Create Redis Server configuration file
  template: dest=/etc/redis.conf
            src=etc/redis/redis.conf.j2
            owner=redis
            group=redis
            mode=0640
  notify: restart redis

# Flush handlers before ensuring the service is started to prevent
# a start and then restart
- name: Flush handlers to apply config changes
  meta: flush_handlers

- name: Ensure Redis Server is running
  service: name=redis state=started
