---
#- name: Installing Redis Sentinel from DEB package
#  apt: pkg=redis-sentinel state=present

- name: Stop and disable Redis Server if not required
  service: 
    name: redis
    state: stopped
    enabled: no
  when: not install_redis_server

- name: Tweak some kernel sysctl values
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  with_items: "{{ sentinel_sysctl_tweaks }}"
