---
- include: repository.yml
  tags: [redis, sentinel]
- include: install_server.yml
#  when: install_redis_server
  tags: [redis]
- include: configure_server.yml
#  when: install_redis_server
  tags: [redis]
- include: install_sentinel.yml
  when: install_redis_sentinel
  tags: [sentinel]
- include: configure_sentinel.yml
  when: install_redis_sentinel
  tags: [sentinel]
- include: local_facts.yml
  tags: [redis, sentinel]
